### ISSUE TITLE
jqr

### ISSUE THREAD

**Issue by JustBerkhout** [mdsumner/nectar#4]
jqr failed in my install. Upon fail (uin the stdout log) it suggests the apt instructions:
add-apt-repository -y ppa:opencpu/jq
apt-get update
apt-get install libjq-dev

after which 
Rscript -e 'install.packages(c("jqr"), "/usr/local/lib/R/site-library")'
succeeds

**Comment by JustBerkhout** [comment]
This resolves these three issues
Warning messages:
1: In install.packages(c("devtools", "sfdct", "rgdal", "leaflet", "rgeos",  :
  installation of package ‘jqr’ had non-zero exit status
2: In install.packages(c("devtools", "sfdct", "rgdal", "leaflet", "rgeos",  :
  installation of package ‘geojson’ had non-zero exit status
3: In install.packages(c("devtools", "sfdct", "rgdal", "leaflet", "rgeos",  :
  installation of package ‘geojsonio’ had non-zero exit status

**Comment by mdsumner** [comment]
I've added this in now, cheers. 

(The raad-client has stalled a bit but it works well, at some point we'll have to formalize the build so it's able to be actually stable - and this will help!)
